### PR TITLE
add CountSymbol method to Gene and Genome types to make it possible to i...

### PR DESCRIPTION
**Pull request by mdejong**
...nspect function and even terminal usage when calculating fitness for a generated Gene

### CODE REVIEW

**Comment by gmlewis** [comment]
Thanks!  I'll check this out once Travis reports no errors:
https://travis-ci.org/gmlewis/gep/jobs/58668336

**Comment by gmlewis** [comment]
Note that although CountSymbol counts the number of times a symbol appears in a `Gene` or `Genome` expression tree, I don't think this is a useful implementation because it does not truly represent the number of times a symbol is used in the resulting code.

For example, let's take a simple `Gene` like `"+.d0.d1.+.+.+.+.d0.d1.d1.d1.d0.d1.d1.d0"`
The counts returned by these functions would be:
```
+ 5
d0 4
d1 6
```
when in reality, the counts are actually only:
```
+ 1
d0 1
d1 1
```
So I think we need to use some of the code-generation algorithm to really determine the true counts of any particular symbol.  Do you want to take a stab at that, or would you like me to?

**Comment by mdejong** [comment]
Humm, to be honest I am still attempting to wrap my head around the whole "head" vs the rest of the gene thing and how some symbols in the Gene are not actually appearing in the generated code. It is quite confusing for example to know what size to pass into the headSize parameter to Model.New(). In looking at the way I was using this function, I was only testing to see if the use count was zero or >= 1 so I was not seeing the problem you describe. I was using it for example to reject randomly generated genes that did not make use of both input terminals when 2 inputs were passed. Please go ahead with the approach you describe as it sounds more useful and general purpose.

**Comment by gmlewis** [comment]
Right... the head vs tail thing is definitely a bit tricky and this evening I just realized that my comments didn't do a very good job of explaining things.  Dr. Ferreira's book obviously is the definitive reference, but in #2 I attempted to add better comments to try and explain things a bit more.

**Comment by gmlewis** [comment]
I've implemented `SymbolCount` in #3 which reflects the true usage of each symbol.
It is a map for all used symbols and is calculated only once when the function is built.
This should give the highest performance and also the greatest accuracy.
`SymbolCount` is implemented both for the `Gene` and the `Genome`.
Closing this PR.  Thank you for the idea!

**Pull request closed without merging**
